---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ include "rabbitmq-topology-operator.fullname" $ }}-webhook-cert'
  labels:
    app.kubernetes.io/name: '{{ include "rabbitmq-topology-operator.name" $ }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  dnsNames:
    - '{{ include "rabbitmq-topology-operator.fullname" $ }}-webhook.{{ .Release.Namespace }}.svc'
    - '{{ include "rabbitmq-topology-operator.fullname" $ }}-webhook.{{ .Release.Namespace }}.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ include "rabbitmq-topology-operator.fullname" $ }}-issuer'
  secretName: '{{ include "rabbitmq-topology-operator.fullname" $ }}-webhook-cert'
