---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: '{{ include "rabbitmq-topology-operator.fullname" $ }}-rolebinding'
  labels:
    app.kubernetes.io/name: '{{ include "rabbitmq-topology-operator.name" $ }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "rabbitmq-topology-operator.fullname" $ }}-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "rabbitmq-topology-operator.fullname" $ }}'
    namespace: '{{ .Release.Namespace }}'
