---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: {{ include "rabbitmq-topology-operator.name" $ }}
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ include "rabbitmq-topology-operator.fullname" $ }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "rabbitmq-topology-operator.name" $ }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: {{ include "rabbitmq-topology-operator.name" $ }}
        app.kubernetes.io/part-of: rabbitmq
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.podAnnotations  }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - command:
            - /manager
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ print .Values.image.registry "/" .Values.image.repository ":" (.Values.image.tag | default .Chart.AppVersion) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources: {{- .Values.resources | toYaml | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - All
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
          {{- with .Values.image.imagePullSecrets  }}
          imagePullSecrets: {{- toYaml . | nindent 12 }}
          {{- end }}
      serviceAccountName: {{ include "rabbitmq-topology-operator.fullname" $ }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
      {{- with .Values.nodeSelector  }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.toleratios  }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity  }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
