---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "rabbitmq-topology-operator.fullname" $ }}-leader-election-rolebinding'
  labels:
    app.kubernetes.io/name: '{{ include "rabbitmq-topology-operator.name" $ }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "rabbitmq-topology-operator.fullname" $ }}-leader-election-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "rabbitmq-topology-operator.fullname" $ }}'
    namespace: '{{ .Release.Namespace }}'
