---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "rabbitmq-topology-operator.fullname" $ }}-webhook'
  labels:
    app.kubernetes.io/name: '{{ include "rabbitmq-topology-operator.name" $ }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    app.kubernetes.io/name: '{{ include "rabbitmq-topology-operator.name" $ }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
