---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  name: '{{ .Release.Name }}-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Release.Name }}-role'
subjects:
  - kind: ServiceAccount
    name: '{{ .Release.Name }}'
    namespace: '{{ .Release.Namespace }}'
