---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: rabbitmq-operator
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/part-of: rabbitmq
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.podAnnotations  }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - command:
            - /manager
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ print .Values.image.registry "/" .Values.image.repository ":" (.Values.image.tag | default .Chart.AppVersion) }}
          name: operator
          ports:
            - containerPort: 9782
              name: metrics
              protocol: TCP
          resources: {{- .Values.resources | toYaml | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.imagePullSecrets  }}
          imagePullSecrets: {{- toYaml . | nindent 12 }}
          {{- end }}
      serviceAccountName: {{ .Release.Name }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector  }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.toleratios  }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity  }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
  replicaCount: {{ .Values.replicaCount }}
