---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  name: rabbitmq-cluster-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rabbitmq-cluster-leader-election-role
subjects:
  - kind: ServiceAccount
    name: rabbitmq-cluster-operator
    namespace: rabbitmq-system
