apiVersion: v2
name: nextcloud-notify_push
description: A Helm chart for nextcloud's push_notify server
type: application
version: 0.4.1
# renovate: image=docker.io/icewind1991/notify_push
appVersion: "1.2.2"
