---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: '{{ include "keycloak-operator.name" $ }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  name: '{{ include "keycloak-operator.fullname" $ }}-view'
  annotations: {}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: '{{ include "keycloak-operator.fullname" $ }}'
    namespace: '{{ .Release.Namespace }}'
