---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/name: '{{ include "keycloak-operator.name" $ }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  name: '{{ include "keycloak-operator.fullname" $ }}-webhook'
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: '{{ include "keycloak-operator.name" $ }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
  type: ClusterIP
