apiVersion: v1
kind: Secret
metadata:
  name: {{ include "draytek-exporter.fullname" . }}
  labels:
    {{- include "draytek-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.exporter.username }}
  {{- if and .value (not .name) }}
  username: {{ .value | b64enc }}
  {{- end }}
  {{- end }}
  {{- with .Values.exporter.password }}
  {{- if and .value (not .name) }}
  password: {{ .value | b64enc }}
  {{- end }}
  {{- end }}