apiVersion: v1
kind: Service
metadata:
  name: {{ include "draytek-exporter.fullname" . }}
  labels:
    {{- include "draytek-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: prometheus
      protocol: TCP
      name: prometheus
  selector:
    {{- include "draytek-exporter.selectorLabels" . | nindent 4 }}
