{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pev2.fullname" . }}
  labels:
    {{- include "pev2.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.username }}
  DB_USER: {{ .Values.secret.username | b64enc }}
  {{- end }}
  {{- with .Values.secret.password }}
  DB_PASS: {{ .Values.secret.password | b64enc }}
  {{- end }}
{{- end -}}