---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rabbitmq-operator
    app.kubernetes.io/name: '{{ include "rabbitmq-cluster-operator.name" $ }}'
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/instance: '{{ .Release.Name }}'
  name: '{{ include "rabbitmq-cluster-operator.fullname" $ }}-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "rabbitmq-cluster-operator.fullname" $ }}-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "rabbitmq-cluster-operator.fullname" $ }}'
    namespace: '{{ .Release.Namespace }}'
