---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ include "rabbitmq-cluster-operator.fullname" $ }}'
  labels:
    app.kubernetes.io/name: '{{ include "rabbitmq-cluster-operator.name" $ }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
