apiVersion: v2
name: powerdns
description: A Helm chart to deploy PowerDNS to Kubernetes
home: https://www.powerdns.com/
type: application
version: 0.9.1
# renovate: image=docker.io/powerdns/pdns-auth-50
appVersion: "5.0.2"
