apiVersion: v2
name: keycloak-operator
description: A Helm chart for Kubernetes
type: application
version: 0.5.11
# renovate: github-releases=keycloak/keycloak
appVersion: 26.4.7

dependencies:
- name: keycloak-operator-crds
  repository: https://schich.tel/helm-charts
  version: 1.4.7
  condition: crds.enabled
