apiVersion: v2
name: keycloak-operator
description: A Helm chart for Kubernetes
type: application
version: 0.4.4
# renovate: github-releases=keycloak/keycloak
appVersion: 26.3.4

dependencies:
- name: keycloak-operator-crds
  repository: https://schich.tel/helm-charts
  version: 1.3.4
  condition: crds.enabled
