apiVersion: v2
name: keycloak-operator
description: A Helm chart for Kubernetes
type: application
version: 0.3.6
# renovate: github-releases=keycloak/keycloak
appVersion: 26.2.5

dependencies:
- name: keycloak-operator-crds
  repository: https://schich.tel/helm-charts
  version: 1.2.5
  condition: crds.enabled
