apiVersion: v2
name: keycloak-operator
description: A Helm chart for Kubernetes
type: application
version: 0.6.6
# renovate: github-releases=keycloak/keycloak
appVersion: 26.5.4

dependencies:
- name: keycloak-operator-crds
  repository: https://schich.tel/helm-charts
  version: 1.5.4
  condition: crds.enabled
