apiVersion: v2
name: keycloak-operator
description: A Helm chart for Kubernetes
type: application
version: 0.2.1
appVersion: 26.0.2

dependencies:
- name: keycloak-operator-crds
  repository: https://schich.tel/helm-charts
  version: 1.1.1
  condition: crds.enabled
