{{- if and .Values.rbac.create .Values.spicedb.dispatchClusterEnabled }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: {{ include "spicedb.fullname" . }}-watch-service
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch"]
{{- end }}