{{- if and .Values.rbac.create .Values.spicedb.dispatchClusterEnabled }}
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: {{ include "spicedb.fullname" . }}-watch-service
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: {{ include "spicedb.fullname" . }}-watch-service
subjects:
  - kind: "ServiceAccount"
    name: {{ include "spicedb.serviceAccountName" . }}
{{- end }}