apiVersion: "v1"
kind: "Service"
metadata:
  name: {{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "grpc"
      port: 50051
      protocol: "TCP"
      targetPort: 50051
    {{- if .Values.spicedb.httpEnabled }}
    - name: "http"
      port: 8443
      protocol: "TCP"
      targetPort: 8443
    {{- end }}
    {{- if .Values.spicedb.dispatchClusterEnabled }}
    - name: "dispatch"
      port: 50053
      protocol: "TCP"
      targetPort: 50053
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: "prometheus"
      port: 9090
      protocol: "TCP"
      targetPort: 9090
    {{- end }}
  selector:
    {{- include "spicedb.selectorLabels" . | nindent 4 }}
