{{- if and .Values.serviceAccount.create .Values.spicedb.dispatchClusterEnabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spicedb.serviceAccountName" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
