apiVersion: v2
name: pev2
description: A Helm chart for the PEV2 application to analyse PG query plans.
type: application
version: 0.3.0
# renovate: image=docker.io/dalibo/explain.dalibo.com
appVersion: "2.20.1"
