apiVersion: v2
name: graylog
home: https://www.graylog.org
version: 0.3.2
# renovate: image=docker.io/graylog/graylog
appVersion: 6.2.4-1
description: Graylog is the centralized log management solution built to open standards for capturing, storing, and enabling real-time analysis of terabytes of machine data.
keywords:
- graylog
- logs
- syslog
- gelf
icon: https://global-uploads.webflow.com/5a218ef7897bf400019e2f16/5a218ef7897bf400019e2f60_logo-graylog.png
sources:
- https://github.com/pschichtel/charts
maintainers:
- name: Phillip Schichtel
  email: phillip@schich.tel
