apiVersion: v2
name: satisfactory
description: A Helm chart for deploying a Satisfactory dedicated game server to Kubernetes.
type: application
version: 0.3.2
# renovate: image=wolveix/satisfactory-server
appVersion: "v1.9.8"
