---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: '{{ .Release.Name }}-webhook-cert'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  dnsNames:
    - '{{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc'
    - '{{ .Release.Name }}-webhook.{{ .Release.Namespace }}.svc.cluster.local'
  issuerRef:
    kind: Issuer
    name: '{{ .Release.Name }}-issuer'
  secretName: '{{ .Release.Name }}-webhook-cert'
