---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: '{{ .Release.Name }}-issuer'
  labels:
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
spec:
  selfSigned: {}
